services:
  postgres:
    image: 'postgres:13'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CDPostgres*123
      POSTGRES_DB: UsersDB
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  rabbitmq:
    image: 'rabbitmq:3-management'
    restart: always
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  users-microservice:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: CDPostgres*123
      DB_NAME: UsersDB
      RABBITMQ_URL: amqp://rabbitmq:5672
    networks:
      - app-network

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: bridge
